language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install flake8

script:
- flake8 --max-line-length=120 instagram_private_api_extensions --exclude=./instagram_private_api_extensions/compat.py

branches:
  only:
    - master
