dist: Trusty
language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media
  - sudo apt-get -y update
  - sudo apt-get install -y ffmpeg
  - mkdir media
  - curl -s -o 'media/test.mp4' 'https://raw.githubusercontent.com/johndyer/mediaelement-files/master/big_buck_bunny.mp4'

install:
  - pip install -r requirements.txt
  - pip install flake8

script:
  - flake8 --max-line-length=120 instagram_private_api_extensions --exclude=./instagram_private_api_extensions/compat.py
  - python -m unittest discover -s tests -v
  - ffmpeg -version

branches:
  only:
    - master
