dist: Trusty
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -y update
  - sudo apt-get install -y ffmpeg
  # Download mpd for live testing
  - curl -s -L -o mpdstub.tar.gz 'https://drive.google.com/uc?export=download&id=0B7NFCwvW5pc3Y0ZTQkUyV3NaSEU'
  - mkdir mpdstub && tar -xzf mpdstub.tar.gz -C mpdstub/
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == '3' ]]; then ((cd mpdstub && python -m http.server 8000) &); fi
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == '2' ]]; then ((cd mpdstub && python -m SimpleHTTPServer 8000);) fi
  # Download media files for media testing
  - mkdir media
  - curl -s -o 'media/test.jpg' 'https://c2.staticflickr.com/6/5267/5669212075_039ed45bff_z.jpg'
  - curl -s -o 'media/test.mp4' 'https://raw.githubusercontent.com/johndyer/mediaelement-files/master/big_buck_bunny.mp4'

install:
  - pip install -r requirements.txt
  - pip install flake8
  # Patch PR 345 https://github.com/Zulko/moviepy/pull/345
  - curl -s -o "$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages/moviepy/tools.py" 'https://raw.githubusercontent.com/jeromegrosse/moviepy/00e911a617eaff63f8e87c6e069d087a8ff6186e/moviepy/tools.py'

script:
  - flake8 --max-line-length=120 instagram_private_api_extensions --exclude=./instagram_private_api_extensions/compat.py
  - python -m unittest discover -s tests -v

branches:
  only:
    - master
