dist: Trusty
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -y update
  - sudo apt-get install -y ffmpeg
  - mkdir media
  - curl -s -o 'media/test.jpg' 'https://c2.staticflickr.com/6/5267/5669212075_039ed45bff_z.jpg'
  - curl -s -o 'media/test.mp4' 'https://raw.githubusercontent.com/johndyer/mediaelement-files/master/big_buck_bunny.mp4'

install:
  - pip install -r requirements.txt
  - pip install flake8
  # Patch PR 345 https://github.com/Zulko/moviepy/pull/345
  - curl -s -o "$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages/moviepy/tools.py" 'https://raw.githubusercontent.com/jeromegrosse/moviepy/00e911a617eaff63f8e87c6e069d087a8ff6186e/moviepy/tools.py'

script:
  - flake8 --max-line-length=120 instagram_private_api_extensions --exclude=./instagram_private_api_extensions/compat.py
  - python -m unittest discover -s tests -v

branches:
  only:
    - master
